apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: c-api-deployment
          image: marayza/hexafood:latest
          ports:
            - containerPort: 3000
          command: ['/bin/sh', '-c']
          args:
            - './wait-for-it.sh postgres-service:5432 -- ./start.sh'
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: app-volume
              mountPath: /home/node/app/vol
      volumes:
        - name: app-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-lb-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 31000
      targetPort: 3000
  selector:
    app: api
